# Generated by Django 4.0.2 on 2022-03-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PendingAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Payment Amount Pending'),
        ),
    ]
