# Generated by Django 4.0.2 on 2022-04-18 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user_pendingamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Contact',
            field=models.BigIntegerField(verbose_name='Mobile no.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Distributor'),
        ),
    ]
