# Generated by Django 4.0.2 on 2022-02-15 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalQuantity', models.SmallIntegerField(default=0, verbose_name='Total Quantity')),
                ('TotalAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Amount')),
                ('CreationDate', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('PaymentDate', models.DateTimeField(verbose_name='Order Payment Date')),
                ('DistributorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor', to=settings.AUTH_USER_MODEL, verbose_name='Distributor')),
                ('RetailerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer', to=settings.AUTH_USER_MODEL, verbose_name='Retailer')),
            ],
        ),
    ]
