# Generated by Django 4.0.2 on 2022-02-15 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderproduct_order_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='orders.order'),
        ),
    ]
