# Generated by Django 4.0.2 on 2022-03-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_id_alter_orderproduct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='PaymentDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Order Payment Date'),
        ),
    ]
